**Import Library**

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import seaborn as sns

**Import DataSet**

In [ ]:
df=pd.read_csv('/content/Womens_Clothing_E-Commerce_Reviews.csv')

In [ ]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [ ]:
df.shape

(23486, 10)

**Missing Values**
remove missing values


In [ ]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
category               14
dtype: int64

In [ ]:
df[df['Review']==""]=np.NaN 

In [ ]:
df['Review'].fillna("No Review",inplace=True)

In [ ]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
category               14
dtype: int64

In [ ]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

**Get Columns**

In [ ]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'category'],
      dtype='object')

In [ ]:
X=df['Review']

In [ ]:
y=df['Rating']

In [ ]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

**Train Test Split**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.7, stratify = y, random_state=132529)


In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

**Get Feature Text Coversion to Tokens**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(lowercase=True, analyzer='word',ngram_range=(2,3),stop_words= 'english',max_features=5000)

In [ ]:
X_train = cv.fit_transform(X_train)

In [ ]:
cv.get_feature_names_out()

array(['10 12', '10 bought', '10 dress', ..., 'years come',
       'yellow color', 'yoga pants'], dtype=object)

In [ ]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_test=cv.fit_transform(X_test)

In [ ]:
cv.get_feature_names_out()

array(['0p fit', '0p fits', '0p fits perfectly', ..., 'years come',
       'years old', 'yoga pants'], dtype=object)

In [ ]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

**Get Model Train**

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model = MultinomialNB()

In [ ]:
model.fit(X_train, y_train)

MultinomialNB()

**Get Model Prediction**

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred.shape

(7046,)

In [ ]:
y_pred

array([5., 5., 5., ..., 5., 3., 1.])

**Get Probability of Each Predicted Class**

In [ ]:
model.predict_proba(X_test)

array([[9.19636335e-03, 5.30126296e-03, 7.50589927e-04, 2.07431991e-02,
        9.64008585e-01],
       [1.05914088e-03, 2.23738440e-03, 3.82466965e-02, 7.48558688e-02,
        8.83600909e-01],
       [1.01993763e-01, 1.17656146e-02, 2.09265775e-01, 1.96033173e-01,
        4.80941674e-01],
       ...,
       [7.18293741e-02, 2.45669520e-02, 6.31679168e-02, 7.49668493e-02,
        7.65468908e-01],
       [1.43415686e-01, 9.97304084e-02, 3.16912120e-01, 1.54025900e-01,
        2.85915885e-01],
       [5.64240400e-01, 2.24392865e-02, 7.91176247e-03, 3.83270531e-01,
        2.21380201e-02]])

**Get Model Evaluation**

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[  25   33   32   33  130]
 [  52   53   77   89  199]
 [  90  105  156  154  356]
 [ 167  145  157  303  751]
 [ 468  322  317  601 2231]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.03      0.10      0.05       253
         2.0       0.08      0.11      0.09       470
         3.0       0.21      0.18      0.20       861
         4.0       0.26      0.20      0.22      1523
         5.0       0.61      0.57      0.59      3939

    accuracy                           0.39      7046
   macro avg       0.24      0.23      0.23      7046
weighted avg       0.43      0.39      0.41      7046



**Recategories Ratings as poor(0) and good(1)**

In [ ]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [ ]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}}, inplace=True)

In [ ]:
y=df['Rating']

In [ ]:
X=df['Review']

**Train Test Split**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.7, stratify = y, random_state=132529)


In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

**Get Feature Text Conversion to Tokens**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True, analyzer='word',ngram_range=(2, 3),stop_words= 'english',
                   max_features=5000)


In [ ]:
X_train = cv.fit_transform(X_train)
X_test=cv.fit_transform(X_test)

**Get Model Re-Train**

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

**Get Model Predictio**n

In [ ]:
y_pred = model.predict(X_test)
y_pred.shape

(7046,)

In [ ]:
y_pred

array([0., 1., 1., ..., 1., 0., 1.])

**Get Model Evaluation**

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[ 428 1155]
 [ 937 4526]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.31      0.27      0.29      1583
         1.0       0.80      0.83      0.81      5463

    accuracy                           0.70      7046
   macro avg       0.56      0.55      0.55      7046
weighted avg       0.69      0.70      0.70      7046

